services:
  course:
    build:
      context: ./course
      dockerfile: Dockerfile
    container_name: course
    ports:
      - '8082:8082'
  student:
    build:
      context: ./student
      dockerfile: Dockerfile
    container_name: student
    ports:
      - '8081:8081'
  enrollment:
    build:
      context: ./enrollment
      dockerfile: Dockerfile
    container_name: enrollment
    ports:
      - '8083:8083'
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - '8080:8080'
    depends_on:
      - course
      - student
      - enrollment
