// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Course struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Description *string    `json:"description,omitempty"`
	Students    []*Student `json:"students,omitempty"`
}

type CourseInput struct {
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Student struct {
	ID      string    `json:"id"`
	Name    string    `json:"name"`
	Email   string    `json:"email"`
	Courses []*Course `json:"courses,omitempty"`
}

type StudentInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}
