# Build the application from source
FROM golang:1.24.0 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /course

# Deploy the application binary into a lean image
FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /course /course

EXPOSE 8082

USER nonroot:nonroot

ENTRYPOINT ["/course"]
